# 1 · Exploración inicial del dataset

**Proyecto:** Predicción de readmisión hospitalaria en pacientes diabéticos
**Dataset:** *Diabetes 130-US hospitals for years 1999-2008* (UCI Machine Learning Repository)
**Autor:** Diego Rodríguez Díaz del Campo

---

### Objetivo de este notebook

Conocer el dataset **antes de tomar ninguna decisión sobre él**. Aquí no se limpia:
se observa, se mide y se documenta. Los únicos cambios que se aplican al fichero son dos
normalizaciones de valores desconocidos: la sustitución del carácter `?` por `NaN` (sin
ella Pandas no puede analizar correctamente los valores ausentes) y la conversión de la
marca `Unknown/Invalid` de `gender` a `NaN`, para que ambos casos reciban el mismo
tratamiento en la limpieza.

Todas las decisiones de limpieza que se detecten aquí se **justifican en las conclusiones**
y se **aplican en el notebook 02**, nunca en este.

| | |
|---|---|
| **Entrada** | `data/raw/diabetic_data.csv` (101.766 × 50) |
| **Salida** | `data/processed/diabetic_data_replaceNaN.csv` |
| **Filas eliminadas** | Ninguna |
| **Cambios aplicados** | `?` → `NaN` en todo el dataset; `Unknown/Invalid` → `NaN` en `gender` |

### Contenido

1. Configuración del entorno y rutas
2. Carga y estructura general
3. Distribución de la variable objetivo y de las variables demográficas
4. Tratamiento del valor `?`
5. Naturaleza de cada variable
6. Variables constantes y registros duplicados
7. Consistencia de las categorías
8. Rangos de las variables numéricas
9. Exportación
10. Conclusiones

## 1 · Configuración del entorno y rutas

Las rutas se definen **una sola vez** con `pathlib` en lugar de escribir la ruta
absoluta en cada celda. Así, si el proyecto cambia de ubicación, basta con
modificar una única línea.

> **Convención del proyecto:** `data/raw/` contiene el dataset original tal y como
> se descargó y **nunca se escribe nada en él**. Todo lo que se genera va a
> `data/processed/`.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

BASE = Path(r'D:\Cosas Diego\Universidad\Proyectos personales\proyecto 1')
RAW = BASE / 'data' / 'raw'
PROC = BASE / 'data' / 'processed'

## 2 · Carga y estructura general

Primer contacto con los datos: cuántos registros hay, qué variables los describen,
de qué tipo son y cuánta variedad contiene cada una.

Cada comprobación va en su propia celda: si se agrupan varias en una sola, Jupyter
solo muestra el resultado de la última y el resto del análisis se pierde.

In [2]:
# low_memory=False evita el DtypeWarning: sin él, Pandas lee el fichero por
# bloques y puede asignar tipos distintos a la misma columna en bloques distintos.

df = pd.read_csv(RAW / 'diabetic_data.csv', low_memory=False)

print(f'Filas: {df.shape[0]}   Columnas: {df.shape[1]}')

Filas: 101766   Columnas: 50

In [3]:
# Tipos de dato y memoria ocupada por cada variable
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [4]:
# Resumen estadístico de las variables almacenadas como numéricas.
# .T transpone la tabla para que cada variable sea una fila y se lea mejor.
df.describe().T

,count,mean,std,min,25%,50%,75%,max
encounter_id,101766.0,1.652016e+08,1.026403e+08,12522.0,84961194.0,152388987.0,2.302709e+08,443867222.0
patient_nbr,101766.0,5.433040e+07,3.869636e+07,135.0,23413221.0,45505143.0,8.754595e+07,189502619.0
admission_type_id,101766.0,2.024006e+00,1.445403e+00,1.0,1.0,1.0,3.000000e+00,8.0
discharge_disposition_id,101766.0,3.715642e+00,5.280166e+00,1.0,1.0,1.0,4.000000e+00,28.0
admission_source_id,101766.0,5.754437e+00,4.064081e+00,1.0,1.0,7.0,7.000000e+00,25.0
time_in_hospital,101766.0,4.395987e+00,2.985108e+00,1.0,2.0,4.0,6.000000e+00,14.0
num_lab_procedures,101766.0,4.309564e+01,1.967436e+01,1.0,31.0,44.0,5.700000e+01,132.0
num_procedures,101766.0,1.339730e+00,1.705807e+00,0.0,0.0,1.0,2.000000e+00,6.0
num_medications,101766.0,1.602184e+01,8.127566e+00,1.0,10.0,15.0,2.000000e+01,81.0
number_outpatient,101766.0,3.693572e-01,1.267265e+00,0.0,0.0,0.0,0.000000e+00,42.0
number_emergency,101766.0,1.978362e-01,9.304723e-01,0.0,0.0,0.0,0.000000e+00,76.0
number_inpatient,101766.0,6.355659e-01,1.262863e+00,0.0,0.0,0.0,1.000000e+00,21.0
number_diagnoses,101766.0,7.422607e+00,1.933600e+00,1.0,6.0,8.0,9.000000e+00,16.0

In [5]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
# Número de valores distintos por variable. Es la primera pista sobre qué
# variables son identificadores, cuáles son categóricas y cuáles constantes.
df.nunique()

encounter_id                101766
patient_nbr                  71518
race                             6
gender                           3
age                             10
weight                          10
admission_type_id                8
discharge_disposition_id        26
admission_source_id             17
time_in_hospital                14
payer_code                      18
medical_specialty               73
num_lab_procedures             118
num_procedures                   7
num_medications                 75
number_outpatient               39
number_emergency                33
number_inpatient                21
diag_1                         717
diag_2                         749
diag_3                         790
number_diagnoses                16
max_glu_serum                    3
A1Cresult                        3
metformin                        4
repaglinide                      4
nateglinide                      4
chlorpropamide                   4
glimepiride                      4
acetohexamide                    2
glipizide                        4
glyburide                        4
tolbutamide                      2
pioglitazone                     4
rosiglitazone                    4
acarbose                         4
miglitol                         4
troglitazone                     2
tolazamide                       3
examide                          1
citoglipton                      1
insulin                          4
glyburide-metformin              4
glipizide-metformin              2
glimepiride-pioglitazone         2
metformin-rosiglitazone          2
metformin-pioglitazone           2
change                           2
diabetesMed                      2
readmitted                       3
dtype: int64

## 3 · Variable objetivo y variables demográficas

`readmitted` es la variable que el proyecto quiere predecir. Sus tres categorías son:

| Valor | Significado |
|---|---|
| `NO` | El paciente no fue readmitido |
| `>30` | Readmitido **después** de 30 días |
| `<30` | Readmitido **antes** de 30 días |

Se revisan también `gender` y `race` porque son las variables donde con más
frecuencia aparecen categorías mal codificadas.

In [7]:
print(df['readmitted'].value_counts(), end='\n\n')
print(df['gender'].value_counts(dropna=False), end='\n\n')
print(df['race'].value_counts(dropna=False))

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

race
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

## 4 · Tratamiento del valor `?`

El dataset original no usa celdas vacías para la información desconocida: usa el
carácter `?`. Para Pandas eso es texto normal, así que `isna()` devolvería cero y
todo el análisis de valores faltantes sería erróneo.

El procedimiento es: **primero medir** cuántos `?` hay en cada columna y **después**
sustituirlos por `NaN`, para que Pandas los reconozca como ausentes.

In [8]:
# Conteo de '?' por columna, antes de sustituir nada
missing_data = (df == '?').sum().sort_values(ascending=False)
missing_data_percentage = (missing_data / len(df)) * 100

print('Porcentaje de valores "?" por columna:')
print(missing_data_percentage[missing_data_percentage > 0])

Porcentaje de valores "?" por columna:
weight               96.858479
medical_specialty    49.082208
payer_code           39.557416
race                  2.233555
diag_3                1.398306
diag_2                0.351787
diag_1                0.020636
dtype: float64

In [9]:
# Sustitución de '?' por NaN en todo el DataFrame
df = df.replace('?', np.nan)

nan_percentage = df.isna().sum() / len(df) * 100

print('Porcentaje de NaN tras la sustitución:')
print(nan_percentage[nan_percentage > 0].sort_values(ascending=False))

Porcentaje de NaN tras la sustitución:
weight               96.858479
max_glu_serum        94.746772
A1Cresult            83.277322
medical_specialty    49.082208
payer_code           39.557416
race                  2.233555
diag_3                1.398306
diag_2                0.351787
diag_1                0.020636
dtype: float64

### 4.1 · Un matiz importante: `max_glu_serum` y `A1Cresult`

Estas dos columnas aparecen con un porcentaje altísimo de `NaN`, pero **no son datos
perdidos**.

En el CSV original su valor es la cadena literal `None` (96.420 y 84.748 filas
respectivamente). Pandas la convierte automáticamente a `NaN` al leer el fichero,
porque `"None"` forma parte de su lista por defecto de valores nulos.

Es decir: el dataset original **sí sabía** el valor, y ese valor significa
*"la prueba no se realizó"*.

La diferencia es clínica, no técnica. Que un médico decida no pedir una hemoglobina
glicosilada es en sí mismo un dato sobre el manejo del paciente. Estas variables no
deben imputarse, sino **recuperar su significado original** con una categoría explícita.

## 5 · Naturaleza de cada variable

Antes de decidir qué se elimina, hay que entender **qué representa** cada columna.
Se revisan todos los valores de todas las variables y, a partir de esa lectura, se
construye un diccionario que clasifica cada una según su naturaleza real.

Este diccionario es la referencia del proyecto: distingue lo que Pandas *cree* que es
una variable (`int64`, `object`) de lo que la variable *es* (un identificador, un
código categórico, una magnitud).

In [10]:
# Revisión de los valores de cada columna
for column in df.columns:
    print(df[column].value_counts(ascending=False, dropna=False), end='\n\n')

encounter_id
2278392      1
190792044    1
190790070    1
190789722    1
190786806    1
            ..
106665324    1
106657776    1
106644876    1
106644474    1
443867222    1
Name: count, Length: 101766, dtype: int64

patient_nbr
88785891     40
43140906     28
1660293      23
88227540     23
23199021     23
             ..
11005362      1
98252496      1
1019673       1
13396320      1
175429310     1
Name: count, Length: 71518, dtype: int64

race
Caucasian          76099
AfricanAmerican    19210
NaN                 2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

weight
NaN          98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

admission_type_id
1    53990
3    18869
2    18480
6     5291
5     4785
8      320
7       21
4       10
Name: count, dtype: int64

discharge_disposition_id
1     60234
3     13954
6     12902
18     3691
2      2128
22     1993
11     1642
5      1184
25      989
4       815
7       623
23      412
13      399
14      372
28      139
8       108
15       63
24       48
9        21
17       14
16       11
19        8
10        6
27        5
12        3
20        2
Name: count, dtype: int64

admission_source_id
7     57494
1     29565
17     6781
4      3187
6      2264
2      1104
5       855
3       187
20      161
9       125
8        16
22       12
10        8
14        2
11        2
25        2
13        1
Name: count, dtype: int64

time_in_hospital
3     17756
2     17224
1     14208
4     13924
5      9966
6      7539
7      5859
8      4391
9      3002
10     2342
11     1855
12     1448
13     1210
14     1042
Name: count, dtype: int64

payer_code
NaN    40256
MC     32439
HM      6274
SP      5007
BC      4655
MD      3532
CP      2533
UN      2448
CM      1937
OG      1033
PO       592
DM       549
CH       146
WC       135
OT        95
MP        79
SI        55
FR         1
Name: count, dtype: int64

medical_specialty
NaN                              49949
InternalMedicine                 14635
Emergency/Trauma                  7565
Family/GeneralPractice            7440
Cardiology                        5352
                                 ...
SportsMedicine                       1
Speech                               1
Perinatology                         1
Neurophysiology                      1
Pediatrics-InfectiousDiseases        1
Name: count, Length: 73, dtype: int64

num_lab_procedures
1      3208
43     2804
44     2496
45     2376
38     2213
       ...
120       1
132       1
121       1
126       1
118       1
Name: count, Length: 118, dtype: int64

num_procedures
0    46652
1    20742
2    12717
3     9443
6     4954
4     4180
5     3078
Name: count, dtype: int64

num_medications
13    6086
12    6004
11    5795
15    5792
14    5707
      ...
70       2
75       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64

number_outpatient
0     85027
1      8547
2      3594
3      2042
4      1099
5       533
6       303
7       155
8        98
9        83
10       57
11       42
13       31
12       30
14       28
15       20
16       15
17        8
21        7
20        7
18        5
22        5
19        3
27        3
24        3
26        2
23        2
25        2
33        2
35        2
36        2
29        2
34        1
39        1
42        1
28        1
37        1
38        1
40        1
Name: count, dtype: int64

number_emergency
0     90383
1      7677
2      2042
3       725
4       374
5       192
6        94
7        73
8        50
10       34
9        33
11       23
13       12
12       10
22        6
16        5
18        5
19        4
20        4
15        3
14        3
25        2
21        2
28        1
42        1
46        1
76        1
37        1
64        1
63        1
54        1
24        1
29        1
Name: count, dtype: int64

number_inpatient
0     67630
1     19521
2      7566
3      3411
4      1622
5       812
6       480
7       268
8       151
9       111
10       61
11       49
12       34
13       20
14       10
15        9
16        6
19        2
17        1
21        1
18        1
Name: count, dtype: int64

diag_1
428    6862
414    6581
786    4016
410    3614
486    3508
       ...
373       1
314       1
684       1
217       1
V51       1
Name: count, Length: 717, dtype: int64

diag_2
276     6752
428     6662
250     6071
427     5036
401     3736
        ...
E918       1
46         1
V13        1
E850       1
927        1
Name: count, Length: 749, dtype: int64

diag_3
250     11555
401      8289
276      5175
428      4577
427      3955
        ...
657         1
684         1
603         1
E826        1
971         1
Name: count, Length: 790, dtype: int64

number_diagnoses
9     49474
5     11393
8     10616
7     10393
6     10161
4      5537
3      2835
2      1023
1       219
16       45
10       17
13       16
11       11
15       10
12        9
14        7
Name: count, dtype: int64

max_glu_serum
NaN     96420
Norm     2597
>200     1485
>300     1264
Name: count, dtype: int64

A1Cresult
NaN     84748
>8       8216
Norm     4990
>7       3812
Name: count, dtype: int64

metformin
No        81778
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64

repaglinide
No        100227
Steady      1384
Up           110
Down          45
Name: count, dtype: int64

nateglinide
No        101063
Steady       668
Up            24
Down          11
Name: count, dtype: int64

chlorpropamide
No        101680
Steady        79
Up             6
Down           1
Name: count, dtype: int64

glimepiride
No        96575
Steady     4670
Up          327
Down        194
Name: count, dtype: int64

acetohexamide
No        101765
Steady         1
Name: count, dtype: int64

glipizide
No        89080
Steady    11356
Up          770
Down        560
Name: count, dtype: int64

glyburide
No        91116
Steady     9274
Up          812
Down        564
Name: count, dtype: int64

tolbutamide
No        101743
Steady        23
Name: count, dtype: int64

pioglitazone
No        94438
Steady     6976
Up          234
Down        118
Name: count, dtype: int64

rosiglitazone
No        95401
Steady     6100
Up          178
Down         87
Name: count, dtype: int64

acarbose
No        101458
Steady       295
Up            10
Down           3
Name: count, dtype: int64

miglitol
No        101728
Steady        31
Down           5
Up             2
Name: count, dtype: int64

troglitazone
No        101763
Steady         3
Name: count, dtype: int64

tolazamide
No        101727
Steady        38
Up             1
Name: count, dtype: int64

examide
No    101766
Name: count, dtype: int64

citoglipton
No    101766
Name: count, dtype: int64

insulin
No        47383
Steady    30849
Down      12218
Up        11316
Name: count, dtype: int64

glyburide-metformin
No        101060
Steady       692
Up             8
Down           6
Name: count, dtype: int64

glipizide-metformin
No        101753
Steady        13
Name: count, dtype: int64

glimepiride-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

metformin-rosiglitazone
No        101764
Steady         2
Name: count, dtype: int64

metformin-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

change
No    54755
Ch    47011
Name: count, dtype: int64

diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [11]:
variable_types = {
    # Identificadores
    'encounter_id': 'identifier',
    'patient_nbr': 'identifier',

    # Variables demográficas
    'race': 'categorical',
    'gender': 'categorical',
    'age': 'ordinal_categorical',
    'weight': 'ordinal_categorical',

    # Información administrativa
    'admission_type_id': 'categorical_code',
    'discharge_disposition_id': 'categorical_code',
    'admission_source_id': 'categorical_code',
    'payer_code': 'categorical',
    'medical_specialty': 'categorical',

    # Información clínica / hospitalaria
    'time_in_hospital': 'numeric',
    'num_lab_procedures': 'numeric',
    'num_procedures': 'numeric',
    'num_medications': 'numeric',
    'number_outpatient': 'numeric',
    'number_emergency': 'numeric',
    'number_inpatient': 'numeric',
    'number_diagnoses': 'numeric',

    # Diagnósticos
    'diag_1': 'diagnosis_code',
    'diag_2': 'diagnosis_code',
    'diag_3': 'diagnosis_code',

    # Resultados de pruebas (ordinales: Norm < >200 < >300 y Norm < >7 < >8)
    'max_glu_serum': 'ordinal_categorical',
    'A1Cresult': 'ordinal_categorical',

    # Medicación
    'metformin': 'categorical',
    'repaglinide': 'categorical',
    'nateglinide': 'categorical',
    'chlorpropamide': 'categorical',
    'glimepiride': 'categorical',
    'acetohexamide': 'categorical',
    'glipizide': 'categorical',
    'glyburide': 'categorical',
    'tolbutamide': 'categorical',
    'pioglitazone': 'categorical',
    'rosiglitazone': 'categorical',
    'acarbose': 'categorical',
    'miglitol': 'categorical',
    'troglitazone': 'categorical',
    'tolazamide': 'categorical',
    'examide': 'categorical',
    'citoglipton': 'categorical',
    'insulin': 'categorical',
    'glyburide-metformin': 'categorical',
    'glipizide-metformin': 'categorical',
    'glimepiride-pioglitazone': 'categorical',
    'metformin-rosiglitazone': 'categorical',
    'metformin-pioglitazone': 'categorical',

    # Cambios / tratamiento de diabetes
    'change': 'categorical',
    'diabetesMed': 'categorical',

    # Variable objetivo
    'readmitted': 'target'
}

print(f'Variables clasificadas: {len(variable_types)}')

Variables clasificadas: 50

## 6 · Variables constantes y registros duplicados

Una variable en la que **todos los pacientes tienen el mismo valor** no puede explicar
por qué unos son readmitidos y otros no: no distingue a nadie de nadie. Ordenar las
variables por número de valores únicos las deja al descubierto de inmediato.

In [12]:
df.nunique(dropna=False).sort_values(ascending=True)

examide                          1
citoglipton                      1
troglitazone                     2
acetohexamide                    2
tolbutamide                      2
glipizide-metformin              2
diabetesMed                      2
metformin-rosiglitazone          2
change                           2
glimepiride-pioglitazone         2
metformin-pioglitazone           2
readmitted                       3
gender                           3
tolazamide                       3
chlorpropamide                   4
glimepiride                      4
glipizide                        4
glyburide                        4
glyburide-metformin              4
acarbose                         4
miglitol                         4
nateglinide                      4
insulin                          4
pioglitazone                     4
rosiglitazone                    4
metformin                        4
A1Cresult                        4
max_glu_serum                    4
repaglinide                      4
race                             6
num_procedures                   7
admission_type_id                8
age                             10
weight                          10
time_in_hospital                14
number_diagnoses                16
admission_source_id             17
payer_code                      18
number_inpatient                21
discharge_disposition_id        26
number_emergency                33
number_outpatient               39
medical_specialty               73
num_medications                 75
num_lab_procedures             118
diag_1                         717
diag_2                         749
diag_3                         790
patient_nbr                  71518
encounter_id                101766
dtype: int64

Dos variables aparecen con **un único valor**:

| Variable | Valores únicos | Contenido |
|---|---|---|
| `examide` | 1 | Todos `"No"` |
| `citoglipton` | 1 | Todos `"No"` |

Son constantes: no aportan ninguna información y son candidatas a eliminación.

In [13]:
# Filas exactamente idénticas en todas sus columnas
print(f'Número de filas duplicadas: {df.duplicated().sum()}')

Número de filas duplicadas: 0

## 7 · Consistencia de las categorías

Los valores de todas las variables de texto ya se han revisado a ojo en la sección 5. Aquí
se comprueba **de forma programática** el problema más habitual en variables de texto: dos
categorías que en realidad son la misma pero difieren por un espacio sobrante o por
mayúsculas (`'Female'` y `'female '`, por ejemplo). Pandas las contaría como distintas y el
recuento de categorías quedaría inflado.

La comprobación consiste en contar las categorías de cada variable antes y después de
normalizar el texto (quitar espacios y pasar a minúsculas). Si el número no cambia, no hay
categorías duplicadas por escritura.

In [14]:
# .str.strip() quita espacios al principio y al final; .str.lower() pasa a minúsculas.
# Si al normalizar se funden categorías, nunique() baja y la variable se imprime.
for column in df.select_dtypes(include='object').columns:
    original    = df[column].nunique()
    normalizado = df[column].str.strip().str.lower().nunique()

    if original != normalizado:
        print(f'{column}: {original} categorías -> {normalizado} tras normalizar')

print('Comprobación terminada.')

Comprobación terminada.

No se detecta ninguna categoría duplicada por escritura: en las 37 variables de texto, el
número de categorías es el mismo antes y después de normalizar.

La única categoría problemática es de otro tipo y ya apareció en la sección 3: `gender`
contiene `Unknown/Invalid` en 3 registros, que no es un género sino una marca de dato no
válido. Se convierte a `NaN` para que reciba el mismo tratamiento que el resto de valores
desconocidos durante la limpieza.

In [15]:
df['gender'] = df['gender'].replace('Unknown/Invalid', np.nan)

print(df['gender'].value_counts(dropna=False))

gender
Female    54708
Male      47055
NaN           3
Name: count, dtype: int64

## 8 · Rangos de las variables numéricas

Última comprobación antes de exportar: verificar que las magnitudes numéricas no
contienen valores imposibles (negativos en recuentos, duraciones desproporcionadas,
etc.) que delatarían errores de registro.

Las variables se seleccionan **desde el diccionario de la sección 5**, no por su `dtype`:
`select_dtypes` devolvería también los identificadores y los códigos `*_id`, que son
enteros pero no magnitudes, y su mínimo y máximo no significan nada.

In [16]:
# Del diccionario, solo las columnas clasificadas como 'numeric'
columnas_numericas = [col for col, tipo in variable_types.items() if tipo == 'numeric']

# .agg(['min', 'max']) aplica las dos funciones a cada columna; .T deja una variable por fila
df[columnas_numericas].agg(['min', 'max']).T

                    min  max
time_in_hospital      1   14
num_lab_procedures    1  132
num_procedures        0    6
num_medications       1   81
number_outpatient     0   42
number_emergency      0   76
number_inpatient      0   21
number_diagnoses      1   16

Las ocho magnitudes se mueven en rangos clínicamente plausibles: estancias de 1 a 14 días,
hasta 132 pruebas de laboratorio, hasta 81 medicaciones y de 1 a 16 diagnósticos. Los
recuentos de visitas previas llegan a 42, 76 y 21, valores altos pero posibles en pacientes
crónicos con uso intensivo del sistema sanitario. **No se corrige ninguna.**

Queda también ilustrado el motivo de haber construido el diccionario: hay columnas
almacenadas como `int64` que no son magnitudes —identificadores y códigos `*_id`— y el tipo
que asigna Pandas no determina la naturaleza de la variable.

## 9 · Exportación

Se guarda el dataset con los `?` y el `Unknown/Invalid` de `gender` ya convertidos a
`NaN`, que será el punto de partida del notebook de limpieza. El fichero original permanece intacto en `data/raw/`.

> **Nota:** `to_csv()` no devuelve un DataFrame, devuelve `None`. Por eso se escribe
> `df.to_csv(...)` y **nunca** `df = df.to_csv(...)`: esto último dejaría `df` valiendo
> `None` y rompería cualquier celda que se ejecutase después.

In [17]:
df.to_csv(PROC / 'diabetic_data_replaceNaN.csv', index=False)

print(f'Guardado en: {PROC / "diabetic_data_replaceNaN.csv"}')
print(f'Dimensiones: {df.shape}')

Guardado en: D:\Cosas Diego\Universidad\Proyectos personales\proyecto 1\data\processed\diabetic_data_replaceNaN.csv
Dimensiones: (101766, 50)

---

## 10 · Conclusiones de la exploración

### Resumen del dataset

| Concepto | Valor |
|---|---|
| Registros (ingresos hospitalarios) | 101.766 |
| Variables | 50 |
| Pacientes distintos | 71.518 |
| Filas duplicadas | 0 |
| Variable objetivo | `readmitted` (`NO` / `>30` / `<30`) |

### Decisiones que se aplicarán en el notebook 02

| Variable | Situación observada | Decisión | Motivo |
|---|---|---|---|
| `weight` | ~97% desconocido | **Eliminar** | Información insuficiente para ser utilizable |
| `examide`, `citoglipton` | Un único valor | **Eliminar** | Constantes: no aportan variabilidad |
| `encounter_id`, `patient_nbr` | Identificadores | **No usar como predictores** | No son características clínicas |
| `medical_specialty` | ~49% desconocido | Categoría `Unknown` | Imputar la moda en la mitad del dataset sería inventar información |
| `payer_code` | ~40% desconocido | Categoría `Unknown` | Mismo criterio |
| `race` | ~2,2% desconocido | Categoría `Unknown` | La ausencia depende del hospital y del registro administrativo: no es aleatoria, y por tanto es informativa |
| `gender` | 3 valores `Unknown/Invalid` | Imputar con la moda | Cantidad insignificante frente a 101.766 registros |
| `diag_1`, `diag_2`, `diag_3` | <1,5% desconocido | Conservar `NaN` | Asignar un diagnóstico artificial no tiene sentido clínico |
| `max_glu_serum`, `A1Cresult` | Cadena `None` leída como `NaN` | Categoría `Not_Measured` | No falta el dato: el dato **es** que la prueba no se hizo |
| Códigos `*_id` | Almacenados como `int64` | Convertir a `category` | Son códigos, no magnitudes |

### Observaciones que condicionan el resto del proyecto

- **El dataset contiene 101.766 ingresos, pero solo 71.518 pacientes distintos.**
  Un mismo paciente aparece en varias filas. Esto no afecta a la limpieza, pero será
  determinante al separar entrenamiento y test: si distintos ingresos del mismo
  paciente caen a ambos lados de la partición, el modelo lo reconocerá y los
  resultados quedarán artificialmente inflados. `patient_nbr` deberá recuperarse en
  ese momento.

- **No hay valores imposibles en las variables numéricas.** Los valores extremos
  observados (por ejemplo, pacientes con muchos ingresos previos) son clínicamente
  plausibles y no se tratarán como errores.

### Siguiente paso

Aplicar estas decisiones de forma controlada y documentada en
**`02_limpieza_dataset.ipynb`**.